apiVersion: v1
kind: Service
metadata:
  name: weight-converter-service
  labels:
    app: weight-converter
spec:
  type: NodePort
  selector:
    app: weight-converter
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30007